#
#  docker-compose.yaml
#  wordpress-better
#
#  Created by Fatih Balsoy on 1/4/22
#  Last Modified by Fatih Balsoy on 1/4/22
#  Copyright © 2022 Fatih Balsoy. All rights reserved.
#

# UPDATE: docker-compose up -d
# STOP: docker-compose down
# DELETE: docker-compose down --volumes

# https://gist.github.com/erikyuzwa/7411752ddcb95b09434aa88f38d91630
version: "3.8"

services:

  database:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./volumes/db_data:/var/lib/mysql
    networks:
      - wordpress-network
    deploy:
      resources:
        limits:
          memory: 2048m

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    env_file: .env
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - wordpress-network

  wordpress:
    depends_on:
      - database
    image: wordpress:beta-6.5-RC3-apache
    restart: unless-stopped
    ports:
      - 8080:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306 # use the same name as database service
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      # - ./wp-content:/var/www/html/wp-content
      #       - '8000:80'
      # persistent local data
      - ./build/material-board:/var/www/html/wp-content/plugins/material-board:cached
      # other data
      - ./volumes/wordpress:/var/www/html
      - ./volumes/plugins:/var/www/html/wp-content/plugins
    networks:
      - wordpress-network

volumes:
  db-data:

networks:
  wordpress-network:
    driver: bridge  