#
#  docker-compose.yaml
#  wordpress-better
#
#  Created by Fatih Balsoy on 1/4/22
#  Last Modified by Fatih Balsoy on 1/4/22
#  Copyright © 2022 Fatih Balsoy. All rights reserved.
#

# UPDATE: docker-compose up -d
# STOP: docker-compose down
# DELETE: docker-compose down --volumes

version: '3'

networks:
  wpsite:

# persistent volumes
volumes:
  db_data:

services:
  # Database
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: 
      # persistent local data
      - .:/var/www/html/wp-content/plugins/testing:delegated
      # other data
      - ./volumes/wordpress:/var/www/html
      - ./volumes/plugins:/var/www/html/wp-content/plugins
    environment:
      # local dev environment
      WORDPRESS_DEBUG: 1
      DEVELOPMENT: 1
      # docker wp config settings
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
