# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & Upload Nightly

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Unix Packages
      - name: Update Ubuntu Package Lists
        run: sudo apt-get update;

      - name: Install zsh
        run: sudo apt-get install zsh

      - name: Install gettext
        run: sudo apt-get install gettext

      # Setup & Build Node.js Project
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Project
        shell: zsh {0}
        run: npm run build

      - name: Get Current Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
      - name: Upload Nightly Build
        uses: actions/upload-artifact@v3
        with:
          name: material-board-nightly-${{ steps.date.outputs.date }}
          path: build/_bundle/material-board
      
      # - name: Upload Nightly Build w/o Date
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: material-board-nightly
      #     path: build/_bundle/material-board
